{% set name = "lightning-flash" %}
{% set version = "0.8.1.post0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-flash-{{ version }}.tar.gz
  sha256: 2586e27ba8c51d92b9e1369469aeba175cbb8dffcee688c94d327a340d6da073

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1.2
    - fsspec
    - jsonargparse[signatures] >=3.17.0, <=4.9.0
    - lightning-utilities >=0.3.0, !=0.4.0
    - numpy <1.24.0
    - packaging
    - pandas >=1.1.0
    - protobuf <=3.20.1
    - pydeprecate ==0.3.1
    - python >=3.7
    - pytorch-lightning >=1.3.6, <2
    - pytorch >=1.7.1
    - requests
    - setuptools <=59.5.0
    - torchmetrics >0.5.1, <0.11.0

test:
  imports:
    - flash
    - flash.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyTorchLightning/lightning-flash
  summary: Your PyTorch AI Factory - Flash enables you to easily configure and run complex AI recipes.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - ethanwharris
    - weiji14
