{% set name = "lightning-flash" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-flash-{{ version }}.tar.gz
  sha256: ee24d00541fe708031b3d3dd30499020dd0627c05d0a23108bd7bd1198d15630

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7.1.2
    - jsonargparse[signatures] >=3.17.0
    - numpy
    - packaging
    - pandas >=1.1.0
    - pydeprecate
    - python >=3.6
    - pytorch-lightning >=1.4.0
    - pytorch >=1.7.1
    - torchmetrics >=0.5.0, !=0.5.1

test:
  imports:
    - flash
    - flash.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyTorchLightning/lightning-flash
  summary: Flash is a framework for fast prototyping, finetuning, and solving most standard deep learning challenges
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - ethanwharris
    - weiji14
