{% set name = "lightning-flash" %}
{% set version = "0.8.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-flash-{{ version }}.tar.gz
  sha256: 9eb0de2c8eac7774c8623decf1cdfd84476df7553152df0ebb552fea997119ac

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - click >=7.1.2
    - fsspec >=2022.5.0
    - jsonargparse[signatures] >=4.22.0
    - lightning-utilities >=0.4.1
    - numpy
    - packaging
    - pandas >1.1.0
    - protobuf
    - pydeprecate >0.2.0
    - python >=3.8
    - pytorch-lightning >=1.8.0, <2.0.0
    - pytorch >1.7.0
    - requests
    - setuptools
    - torchmetrics >0.7.0, <0.11.0

test:
  imports:
    - flash
    - flash.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyTorchLightning/lightning-flash
  summary: Your PyTorch AI Factory - Flash enables you to easily configure and run complex AI recipes.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - ethanwharris
    - weiji14
