{% set name = "lightning-flash" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-flash-{{ version }}.tar.gz
  sha256: 7a409f9dd903fd6173bf42f9d42ab082311dc130db7ce1d33ba50e23e23b0020

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7.1.2
    - jsonargparse[signatures] >=3.17.0
    - numpy
    - packaging
    - pandas <1.3.0
    - pydeprecate
    - python >=3.6
    - pytorch-lightning >=1.3.1
    - pyyaml >=5.1
    - pytorch >=1.7
    - torchmetrics <=0.5.0
    - tqdm

test:
  imports:
    - flash
    - flash.core
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PyTorchLightning/lightning-flash
  summary: Flash is a framework for fast prototyping, finetuning, and solving most standard deep learning challenges
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Borda
    - ethanwharris
    - weiji14
